os: linux
arch:
 - amd64
 - ppc64le
language: node_js
node_js:
  - "node"
dist: trusty
sudo: true
addons:
    chrome: stable
before_install:
  - npm install -g grunt-cli bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
